# Generated by Django 3.0.6 on 2020-05-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'VG'), ('Fruit', 'FR'), ('Milk', 'MI')], max_length=200, null=True),
        ),
    ]
