# Generated by Django 3.0.6 on 2020-05-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20200514_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VG', 'Vegetables'), ('FR', 'Fruit'), ('MI', 'Milk')], max_length=200, null=True),
        ),
    ]
